# Generated by Django 4.2.27 on 2026-01-29 12:51

from django.db import migrations, models
import personas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=100)),
                ('rut', models.CharField(help_text='RUT sin puntos (ej: 12345678-9)', max_length=12, unique=True, validators=[personas.models.validar_rut])),
                ('organizacion', models.CharField(blank=True, help_text='Organización o institución', max_length=150, null=True)),
                ('fono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
    ]
